version: "3.3"

networks:
  local-validator-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.1.0/24

services:

  validator1:
    image: "dojima"
    build: .
    container_name: validator1
    privileged: true
    networks:
      - local-validator-network
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    ports:
      - "2201:22"
      - "1317:1317"
      - "26657:26657"
      - "26656:26656"
      - "8545:8545"
      - "8546:8546"
    
  validator2:
    image: "dojima"
    build: .
    container_name: validator2
    privileged: true
    networks:
      - local-validator-network
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    ports:
      - "2202:22"
      - "1318:1317"
      - "26659:26657"
      - "26658:26656"
      - "8547:8545"
      - "8548:8546"